### ISSUE TITLE
negatif anlam

### ISSUE THREAD

**Issue by candasm** [derinogrenme/2016summit.derinorgrenme.com#1]
Arama, bulma, ogrenme sonuna -ma, -me gelince anlam negatif gibi oluyor. Derinogren'in daha guzel olacagi kanisindayim.

**Comment by ferhatkurt** [comment]
Türk Dil Kurumu'nun Büyük Türkçe Sözlüğü'nde (http://www.tdk.gov.tr/index.php?option=com_bts&view=bts) **öğren ** kelimesi yer almamaktadır. İlginç değil mi?
Belirttiğiniz konu bir şekilde herkes tarafından bilindiği için derin öğrenme şeklinde kalmasının şu aşamada daha uygun olacağı kanısındayım.
Değerli katkınız için teşekkür ediyorum. Umarım bizimle iletişim kurmaya devam edersiniz.

**Comment by candasm** [comment]
Ara ve aramak icinde ayni konu gecerli ara'nin aramak gibi bir anlam ifade ettigi yok fakat eylem olarak kullaniliyor. Anladigim kadariyla bu konu deep learning'den bire bir cevrildigi icin boyle olmus.

**Comment by ferhatkurt** [comment]
Arama Motoru ifadesinde olduğu gibi derin öğrenmeyi kullanmaya devam
ediyoruz. Görüşmek üzere.

5 Şubat 2016 14:40 tarihinde Candaş Minareci <notifications@github.com>
yazdı:
